// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: email_tokens.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createEmailToken = `-- name: CreateEmailToken :exec
INSERT INTO email_tokens (
    user_id,
    token_hash,
    type,
    expires_at
) VALUES ($1, $2, $3, $4)
`

type CreateEmailTokenParams struct {
	UserID    pgtype.UUID
	TokenHash string
	Type      string
	ExpiresAt pgtype.Timestamp
}

func (q *Queries) CreateEmailToken(ctx context.Context, arg CreateEmailTokenParams) error {
	_, err := q.db.Exec(ctx, createEmailToken,
		arg.UserID,
		arg.TokenHash,
		arg.Type,
		arg.ExpiresAt,
	)
	return err
}

const getValidEmailToken = `-- name: GetValidEmailToken :one
SELECT id, user_id, token_hash, type, expires_at, used_at, created_at
FROM email_tokens
WHERE token_hash = $1
  AND type = $2
  AND used_at IS NULL
  AND expires_at > now()
`

type GetValidEmailTokenParams struct {
	TokenHash string
	Type      string
}

func (q *Queries) GetValidEmailToken(ctx context.Context, arg GetValidEmailTokenParams) (EmailToken, error) {
	row := q.db.QueryRow(ctx, getValidEmailToken, arg.TokenHash, arg.Type)
	var i EmailToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TokenHash,
		&i.Type,
		&i.ExpiresAt,
		&i.UsedAt,
		&i.CreatedAt,
	)
	return i, err
}

const markEmailTokenUsed = `-- name: MarkEmailTokenUsed :exec
UPDATE email_tokens
SET used_at = now()
WHERE id = $1
`

func (q *Queries) MarkEmailTokenUsed(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, markEmailTokenUsed, id)
	return err
}
