// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: session.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createSession = `-- name: CreateSession :one
INSERT INTO sessions
(user_id, refresh_token_hash, device_name, device_info, ip_address, expires_at)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, user_id, refresh_token_hash, device_name, device_info, ip_address, expires_at, created_at, last_used, revoked_at
`

type CreateSessionParams struct {
	UserID           pgtype.UUID
	RefreshTokenHash string
	DeviceName       pgtype.Text
	DeviceInfo       pgtype.Text
	IpAddress        pgtype.Text
	ExpiresAt        pgtype.Timestamp
}

func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) (Session, error) {
	row := q.db.QueryRow(ctx, createSession,
		arg.UserID,
		arg.RefreshTokenHash,
		arg.DeviceName,
		arg.DeviceInfo,
		arg.IpAddress,
		arg.ExpiresAt,
	)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.RefreshTokenHash,
		&i.DeviceName,
		&i.DeviceInfo,
		&i.IpAddress,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.LastUsed,
		&i.RevokedAt,
	)
	return i, err
}

const getSessionById = `-- name: GetSessionById :one
SELECT id, user_id, refresh_token_hash, device_name, device_info, ip_address, expires_at, created_at, last_used, revoked_at
FROM sessions
WHERE id = $1
    AND revoked_at IS NULL
    AND expires_at > now()
`

func (q *Queries) GetSessionById(ctx context.Context, id pgtype.UUID) (Session, error) {
	row := q.db.QueryRow(ctx, getSessionById, id)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.RefreshTokenHash,
		&i.DeviceName,
		&i.DeviceInfo,
		&i.IpAddress,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.LastUsed,
		&i.RevokedAt,
	)
	return i, err
}

const getSessionByRefreshToken = `-- name: GetSessionByRefreshToken :one
SELECT id, user_id, refresh_token_hash, device_name, device_info, ip_address, expires_at, created_at, last_used, revoked_at
FROM sessions
WHERE refresh_token_hash = $1
  AND revoked_at IS NULL
  AND expires_at > now()
`

func (q *Queries) GetSessionByRefreshToken(ctx context.Context, refreshTokenHash string) (Session, error) {
	row := q.db.QueryRow(ctx, getSessionByRefreshToken, refreshTokenHash)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.RefreshTokenHash,
		&i.DeviceName,
		&i.DeviceInfo,
		&i.IpAddress,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.LastUsed,
		&i.RevokedAt,
	)
	return i, err
}

const listActiveUserSessions = `-- name: ListActiveUserSessions :many
SELECT id, user_id, refresh_token_hash, device_name, device_info, ip_address, expires_at, created_at, last_used, revoked_at
FROM sessions
WHERE user_id = $1
  AND revoked_at IS NULL
  AND expires_at > now()
ORDER BY last_used DESC
`

func (q *Queries) ListActiveUserSessions(ctx context.Context, userID pgtype.UUID) ([]Session, error) {
	rows, err := q.db.Query(ctx, listActiveUserSessions, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Session
	for rows.Next() {
		var i Session
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.RefreshTokenHash,
			&i.DeviceName,
			&i.DeviceInfo,
			&i.IpAddress,
			&i.ExpiresAt,
			&i.CreatedAt,
			&i.LastUsed,
			&i.RevokedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const revokeAllSessions = `-- name: RevokeAllSessions :exec
UPDATE sessions
SET revoked_at = now()
WHERE revoked_at IS NULL
`

func (q *Queries) RevokeAllSessions(ctx context.Context) error {
	_, err := q.db.Exec(ctx, revokeAllSessions)
	return err
}

const revokeAllUserSessions = `-- name: RevokeAllUserSessions :exec
UPDATE sessions
SET revoked_at = now()
WHERE user_id = $1
  AND revoked_at IS NULL
`

func (q *Queries) RevokeAllUserSessions(ctx context.Context, userID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, revokeAllUserSessions, userID)
	return err
}

const revokeSession = `-- name: RevokeSession :exec
UPDATE sessions
SET revoked_at = now()
WHERE id = $1
  AND revoked_at IS NULL
`

func (q *Queries) RevokeSession(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, revokeSession, id)
	return err
}

const rotateSessionToken = `-- name: RotateSessionToken :exec
UPDATE sessions
SET refresh_token_hash = $2,
    last_used = now()
WHERE id = $1
  AND revoked_at IS NULL
  AND expires_at > now()
`

type RotateSessionTokenParams struct {
	ID               pgtype.UUID
	RefreshTokenHash string
}

func (q *Queries) RotateSessionToken(ctx context.Context, arg RotateSessionTokenParams) error {
	_, err := q.db.Exec(ctx, rotateSessionToken, arg.ID, arg.RefreshTokenHash)
	return err
}

const updateSessionLastUsed = `-- name: UpdateSessionLastUsed :exec
UPDATE sessions
SET last_used = now()
WHERE id = $1
  AND revoked_at IS NULL
  AND expires_at > now()
`

func (q *Queries) UpdateSessionLastUsed(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, updateSessionLastUsed, id)
	return err
}
